### ISSUE TITLE
file encoding help wanted

### ISSUE THREAD

**Issue by Eunsolfs** [MistEO/meojson#14]
When the file encoding is utf8 or utf-8 bom, the json::open function reads Chinese fields with garbled characters

This problem was solved after changing the json file encoding to GB2312.
So is it possible to automatically detect the file encoding from the code level and deal with it accordingly?

Or take violent means: directly and automatically modify the file encoding to GB2312 ？？
Or specify the encoding when opening the file?

-------------------------------------------------------------------------------------------------------

当文件编码为utf8 或utf-8 bom时，json::open函数读取中文字段会乱码

这个问题在将json文件编码改为GB2312后得以解决。
所以是否能从代码层面，自动检测文件编码并予以对应的处理

或者采取暴力的手段：直接自动修改文件编码为GB2312 ？？
或者在打开文件时指定编码？

**Comment by MistEO** [comment]
不会乱码，读到的是什么，as_string 仍然是什么，区别在于你自己什么把它打印或者显示出来。（不信可以把 as_string 写到文件里再看看
