### ISSUE TITLE
32位环境下会编译错误而非正确的禁用packed_bytes_trait_uint64

### ISSUE THREAD

**Issue by neko-para** [MistEO/meojson#24]
```cpp
    using value_type = std::enable_if_t<sizeof(void*) >= 8, uint64_t>;
```
表达式在32位环境下直接导致后续使用value_type错误, 应当考虑改为
```cpp
    using value_type = uint64_t;
```
以及后续的
```cpp
template <>
struct packed_bytes<8> {
    using traits = std::enable_if_t<packed_bytes_trait_uint64::available, packed_bytes_trait_uint64>;
};
```
也应当考虑使用
```cpp
template <>
struct packed_bytes<8> {
    using traits = packed_bytes_trait_uint64;
};
```
由于最后对packed_bytes_trait_max的计算应该可以正确根据available判定, 因此上述修改应该只是单纯确保32位环境下能够编译通过.

**Comment by MistEO** [comment]
@dantmnf dant 带带

**Comment by ChingCdesu** [comment]
> ```c++
>     using value_type = std::enable_if_t<sizeof(void*) >= 8, uint64_t>;
> ```
> 
> 表达式在32位环境下直接导致后续使用value_type错误, 应当考虑改为
> 
> ```c++
>     using value_type = uint64_t;
> ```
> 
> 以及后续的
> 
> ```c++
> template <>
> struct packed_bytes<8> {
>     using traits = std::enable_if_t<packed_bytes_trait_uint64::available, packed_bytes_trait_uint64>;
> };
> ```
> 
> 也应当考虑使用
> 
> ```c++
> template <>
> struct packed_bytes<8> {
>     using traits = packed_bytes_trait_uint64;
> };
> ```
> 
> 由于最后对packed_bytes_trait_max的计算应该可以正确根据available判定, 因此上述修改应该只是单纯确保32位环境下能够编译通过.

踹一脚，让你来搞maa-x

**Comment by dantmnf** [comment]
小插曲：packed_bytes_trait_uint32 性能跟 packed_bytes_trait_uint64 差不多（
