### ISSUE TITLE
建议：希望提供选项，能让json保持添加的顺序，并且支持格式化功能

### ISSUE THREAD

**Issue by Sallee1** [MistEO/meojson#26]
1. 现在的json模块在序列化时会按照字典序排列object的成员

比如原本的顺序：

```json
{
	"id": 1,
	"name": "名字",
	"value": "NAME",
	"chunks": [{
		"path": "name.png",
		"rect": [0, 0, 1000, 1000]
	}]
}
```

在反序列化后再次序列化，会变成这样

```json
{
	"chunks": [{
		"path": "name.png",
		"rect": [0, 0, 1000, 1000]
	}],
	"id": 1,
	"name": "名字",
	"value": "NAME"
}
```
顺序会发生变化，虽然不影响解析，但如果要手工编辑json，那的确会带来一些麻烦

2. 能否提供简单的格式化功能

1中的输出实际上是：

```json
{"chunks":[{"path":"name.png","rect":[0,0,1000,1000]}],"id":1,"name":"名字","value":"NAME"}
```

会变成单行，更难读了

**Comment by MistEO** [comment]
- Json 标准规定 Json object 就是乱序的，不打算做排序功能
- 输出可以用 `.dumps(4)`

**Comment by Sallee1** [comment]
不是说排序，而是输出是被“排序”过的（应该是std::map自排序的原因），而不是按照添加的顺序排列

**Comment by MistEO** [comment]
按照添加的顺序排列 -> object 是有序的
输出看起来是被“排序”过的 -> object 是无序的，这个“序”取决于 json 库的实现
