### ISSUE TITLE
benchmark把我内存打爆了...

### ISSUE THREAD

**Issue by JYLeeLYJ** [MistEO/meojson#3]
![image](https://user-images.githubusercontent.com/30959553/144264364-7160b87c-9c74-41d1-ba3c-bc2db0449684.png)

loop_time次parse的数据应该是都存在dom里，没有回收
这样bench应该不太准，看看是否需要修正一下

https://github.com/MistEO/meojson/blob/7a8b36adf72793513261661b35c3650a66df1b2d/test/parse/rapidjson_performance_test.cpp#L32-L38

**Comment by MistEO** [comment]
我不跑分啦！
