### ISSUE TITLE
std::Array貌似不支持序列化

### ISSUE THREAD

**Issue by Sallee1** [MistEO/meojson#46]

**Comment by Sallee1** [comment]
比如，我要序列化以两点表示的矩形
我使用的容器为`std::Array<std::Array<float,2>,2>`
这种定长数组是无法序列化的
如果修改成变长数组，如`std::Vector<std::Array<float>>`就可以了

**Comment by MistEO** [comment]
std::array 没法直接 emplace，得单独写逻辑，有点麻烦，摆烂了（

**Comment by windsgo** [comment]
> std::array 没法直接 emplace，得单独写逻辑，有点麻烦，摆烂了（

玛丽玛丽不要摆，快快实现用户的需求。(我自己用下来的感觉是作为配置文件序列化功能时，stdarray用的更多(用vec的话感觉很多情况下也得from完再判断长度是否对，要是直接支持array然后长度不匹配抛异常就好了)，然后我就只能自己实现from/to，一个一个拷贝
