### ISSUE TITLE
调用 unicode::findInRange 的各种 unicode判断函数是否有问题？

### ISSUE THREAD

**Issue by qiechenxian** [MistEO/meojson#48]
如 https://github.com/MistEO/meojson/blob/master/include/parser5/unicode.h 中的 space_separator数组，存在以下unicode序列 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005，其明显不是以
{ start1, end1, start2, end2, ... } 的形式保存的。

且 https://www.compart.com/en/unicode/category/Zs 中显示0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005 均为 Space Separator

**Comment by MistEO** [comment]
@ChingCdesu

**Comment by ChingCdesu** [comment]
#35 查看这个pr
unicode.h是从代码生成器生成的
